export const ADD_CANDIDATE = "ADD_CANDIDATE";
export const REMOVE_CANDIDATE = "REMOVE_CANDIDATE";
export const CHANGE_CANDIDATE_NAME = "CHANGE_CANDIDATE_NAME";
export const CHANGE_BALLOT_ARG = "CHANGE_BALLOT_ARG";